services:
  songsfetch:
    build: .
    container_name: songsfetch
    ports:
      - "3000:3000"
    volumes:
      - ./music:/music
    environment:
      - SONGSFETCH_OUTPUT_DIR=/music
      - EVENTLET_NO_GREENDNS=yes
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
